"""Deterministic derived index for unified-git-state.

`_index.md` is a build artifact, not source: it is regenerated by scanning all
session manifests (stable sort by started_at, conversation_id) and the per-file
stream store, then rendered with a fixed preamble/header. Two regenerations are
byte-identical, so the index is convergent and never produces a structural merge
conflict. Friendly NNN numbers preserve distinct stored numbers; genuine
collisions (two manifests with the SAME number) are normalized deterministically
by (started_at, conversation_id) so concurrent starts self-heal without ever
creating a new collision. Stays at `.archive/transcripts/_index.md`.

Stdlib only; Python 3.12+. Malformed manifests are skipped-with-warning by
iter_manifests; a hostile manifest can never abort a full regen.
"""
from __future__ import annotations

from pathlib import Path

import _manifest
import _streams

PREAMBLE = """# Conversation Transcripts Archive

This index is a DERIVED build artifact. Do not hand-edit — it is regenerated
from the per-session manifests in `.archive/sessions/*/manifest.json` and the
per-stream files in `.archive/streams/*.json`. Two regenerations are
byte-identical.

## Streams
"""

INDEX_HEADER = """## Transcript Index
"""


def _sort_key(m: dict) -> tuple[str, str]:
    return (m.get("started_at") or "", m.get("conversation_id") or "")


def _assign_numbers(manifests: list[dict]) -> list[int]:
    """Assign a unique display number to each manifest (sorted order).

    Distinct stored `number` values are preserved as-is. Genuine collisions
    (two manifests sharing the same stored number) are tie-broken by sort order
    (started_at, conversation_id): the earlier keeps it, later ones bump to the
    next free number. Assignment is deterministic and can never produce a new
    collision — every entry receives a unique number.
    """
    used: set[int] = set()
    display: list[int] = []
    for i, m in enumerate(manifests, start=1):
        raw = m.get("number")
        try:
            base = int(raw)
        except (TypeError, ValueError):
            base = i  # no stored number: seed from positional rank
        n = base
        while n in used:
            n += 1
        used.add(n)
        display.append(n)
    return display


def _render_streams(archive_dir: Path) -> str:
    streams = _streams.list_streams(archive_dir)
    header = ("| Slug | Name | Status | Claim | Since | Last Touched | "
              "Last Handoff | Branch | Worktree |")
    sep = "| --- | --- | --- | --- | --- | --- | --- | --- | --- |"
    lines = [header, sep]
    for s in streams:
        cells = [
            s.slug, s.name, s.status,
            s.claim if s.claim is not None else "unclaimed",
            s.since if s.since is not None else "—",
            s.last_touched or "",
            s.last_handoff if s.last_handoff is not None else "",
            s.branch if s.branch is not None else "",
            s.worktree if s.worktree is not None else "",
        ]
        lines.append("| " + " | ".join(cells) + " |")
    return "\n".join(lines)


def _render_session(m: dict, number: int) -> str:
    title = m.get("title") or "(untitled)"
    files = m.get("files") or {}
    transcript = files.get("transcript") or "(no transcript)"
    started = m.get("started_at") or ""
    ended = m.get("ended_at") or ("[In Progress]"
                                  if m.get("status") != "complete" else "")
    stream = m.get("stream") or "—"
    contributor = m.get("contributor") or ""
    model = m.get("model") or ""
    return (
        f"### {number:03d} - {title}\n"
        f"**File**: {transcript}\n"
        f"**Started**: {started}\n"
        f"**Ended**: {ended}\n"
        f"**Stream**: {stream}\n"
        f"**Participants**: {contributor}, {model}\n"
        f"**Session**: {m.get('session_id') or m.get('conversation_id') or ''}"
    )


def generate_index(archive_dir: Path) -> str:
    """Render the full `_index.md` text deterministically. Pure (no writes)."""
    archive_dir = Path(archive_dir)
    manifests = sorted(_manifest.iter_manifests(archive_dir), key=_sort_key)

    # Preserve distinct stored numbers; normalize genuine collisions by sort
    # order without creating a new collision (every entry gets a unique NNN).
    numbers = _assign_numbers(manifests)
    entries = [_render_session(m, n) for m, n in zip(manifests, numbers)]

    parts = [PREAMBLE.rstrip("\n"), "",
             _render_streams(archive_dir), "",
             INDEX_HEADER.rstrip("\n"), ""]
    parts.append("\n\n".join(entries) if entries else "_(no sessions yet)_")
    return "\n".join(parts).rstrip("\n") + "\n"


def write_index(archive_dir: Path) -> Path:
    """Regenerate and write `.archive/transcripts/_index.md`. Returns the path."""
    archive_dir = Path(archive_dir)
    target = archive_dir / "transcripts" / "_index.md"
    target.parent.mkdir(parents=True, exist_ok=True)
    import os
    tmp = target.with_suffix(".md.tmp")
    tmp.write_text(generate_index(archive_dir), encoding="utf-8")
    os.replace(tmp, target)
    return target
